"""remove chatmessage relationship

Revision ID: 02fd6b22235b
Revises: e92cdadddcfb
Create Date: 2025-04-27 06:29:11.145278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fd6b22235b'
down_revision: Union[str, None] = 'e92cdadddcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
