"""Focus only ChatMessage table

Revision ID: 1fe7b4a22276
Revises: d7cb27b6a737
Create Date: 2025-04-27 05:50:51.236720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe7b4a22276'
down_revision: Union[str, None] = 'd7cb27b6a737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatMessage',
    sa.Column('chatMessageId', sa.Integer(), nullable=False),
    sa.Column('benefitId', sa.Integer(), nullable=False),
    sa.Column('authorType', sa.Enum('USER', 'AI', name='authortype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createdBy', sa.String(length=255), server_default='flask-service', nullable=True),
    sa.Column('updatedBy', sa.String(length=255), server_default='flask-service', nullable=True),
    sa.PrimaryKeyConstraint('chatMessageId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChatMessage')
    # ### end Alembic commands ###
