"""change chatmessage relationship

Revision ID: e92cdadddcfb
Revises: 1fe7b4a22276
Create Date: 2025-04-27 06:22:27.090277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92cdadddcfb'
down_revision: Union[str, None] = '1fe7b4a22276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
